version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "tutorial_db"
    ports:
      - "5432:5432"
    volumes:
      - tutorial_postgres_data:/var/lib/postgresql/tutorial_data

volumes:
  tutorial_postgres_data:
    driver: local